# Generated by Django 4.2.4 on 2023-09-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='v_status',
            field=models.CharField(default='unverified', max_length=10),
        ),
    ]
