# Generated by Django 4.2.1 on 2023-09-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_authentication_v_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='', max_length=100)),
                ('service_price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_services',
            },
        ),
    ]
