# Generated by Django 4.2.1 on 2023-09-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=100)),
                ('client_email', models.CharField(default='', max_length=100)),
                ('client_number', models.IntegerField(default=0)),
                ('appointment_date', models.CharField(default='', max_length=100)),
                ('appointment_time', models.CharField(default='', max_length=100)),
                ('service_id', models.IntegerField(default=0)),
                ('appointment_status', models.CharField(default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'tbl_appointment',
            },
        ),
    ]
