# Generated by Django 4.2.1 on 2023-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='service_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointments',
            name='service_price',
            field=models.IntegerField(default=0),
        ),
    ]
