# Generated by Django 4.2.4 on 2023-09-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_services_service_description_services_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_img',
            field=models.ImageField(upload_to='image_uploads'),
        ),
    ]
