# Generated by Django 4.2.1 on 2023-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_alter_services_service_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='dtr_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_vid', models.CharField(default='', max_length=200)),
                ('am_in', models.CharField(default='', max_length=20, null=True)),
                ('am_out', models.CharField(default='', max_length=20, null=True)),
                ('pm_in', models.CharField(default='', max_length=20, null=True)),
                ('pm_out', models.CharField(default='', max_length=20, null=True)),
                ('date', models.CharField(default='', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_dtr',
            },
        ),
    ]
