# Generated by Django 4.2.1 on 2023-09-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_dtr_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_vid', models.CharField(default='', max_length=200)),
                ('appointment_id', models.IntegerField(default=0)),
                ('time', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'tbl_employee_schedule',
            },
        ),
    ]
