# Generated by Django 4.2.1 on 2023-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_employee_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_schedule',
            name='status',
            field=models.CharField(default='To Pay', max_length=20),
        ),
    ]
