# Generated by Django 4.2.1 on 2023-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0011_ratings_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings_comments',
            name='ratings',
            field=models.IntegerField(default=5),
        ),
    ]
