# Generated by Django 4.2.1 on 2023-09-22 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_alter_ratings_comments_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings_comments',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
