# Generated by Django 4.2.1 on 2023-09-22 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0013_ratings_comments_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='replies_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(default='', max_length=200)),
                ('comment_id', models.IntegerField(default=0)),
                ('replies', models.CharField(default='', max_length=5000, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tbl_comment_replies',
            },
        ),
    ]
