# Generated by Django 4.2.1 on 2023-09-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0014_replies_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings_comments',
            name='replied',
            field=models.CharField(default='false', max_length=10, null=True),
        ),
    ]
