# Generated by Django 4.2.1 on 2023-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0015_ratings_comments_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
