# Generated by Django 4.2.1 on 2023-09-23 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0016_services_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtr_record',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
