# Generated by Django 4.2.1 on 2023-09-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0017_alter_dtr_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtr_record',
            name='date',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
