# Generated by Django 4.2.1 on 2023-09-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0018_alter_dtr_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtr_record',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
