# Generated by Django 4.2.1 on 2023-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0019_dtr_record_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
