# Generated by Django 4.2.1 on 2023-10-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0020_alter_services_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='client_number',
            new_name='phone_number',
        ),
    ]
