# Generated by Django 4.2.1 on 2023-10-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0022_rename_phone_number_appointments_client_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='client_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
