# Generated by Django 4.2.1 on 2024-01-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0023_alter_appointments_client_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='employment_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_v_id', models.CharField(default='', max_length=200)),
                ('basic_monthly_pay', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_employment_data',
            },
        ),
    ]
